-- ==========================================================
-- Matéria: 5SBD - Programação de Scripts de Banco de Dados
-- Atividade: Atividade Prática 01: Implantação do Modelo Físico
-- Ferramenta: Oracle APEX | Turno: Manhã | 2026.2 | Aluna: Manuelle
-- ==========================================================

-- Objetivo: Escrever e executar os comandos DDL (Data Definition 
-- Language) no ambiente Oracle APEX para criar as 6 tabelas 
-- fundamentais do sistema, configurando PK, FK, UNIQUE e CHECK.

-- 1. LIMPEZA DA BASE
DROP TABLE tb_venda_item CASCADE CONSTRAINTS;
DROP TABLE tb_venda CASCADE CONSTRAINTS;
DROP TABLE tb_produto CASCADE CONSTRAINTS;
DROP TABLE tb_categoria CASCADE CONSTRAINTS;
DROP TABLE tb_vendedor CASCADE CONSTRAINTS;
DROP TABLE tb_cliente CASCADE CONSTRAINTS;

-- 2. TABELAS INDEPENDENTES

CREATE TABLE tb_cliente (
    id_cliente NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_tb_cliente PRIMARY KEY,
    nome VARCHAR2(150) NOT NULL,
    email VARCHAR2(150) NOT NULL CONSTRAINT uk_cliente_email UNIQUE,
    cpf VARCHAR2(11) NOT NULL CONSTRAINT uk_cliente_cpf UNIQUE,
    ativo CHAR(1) DEFAULT 'S' NOT NULL CONSTRAINT ck_cliente_ativo CHECK (ativo IN ('S', 'N'))
);

CREATE TABLE tb_vendedor (
    id_vendedor NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_tb_vendedor PRIMARY KEY,
    nome VARCHAR2(150) NOT NULL,
    email VARCHAR2(150) NOT NULL CONSTRAINT uk_vendedor_email UNIQUE,
    ativo CHAR(1) DEFAULT 'S' NOT NULL CONSTRAINT ck_vendedor_ativo CHECK (ativo IN ('S', 'N'))
);

CREATE TABLE tb_categoria (
    id_categoria NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_tb_categoria PRIMARY KEY,
    nome VARCHAR2(50) NOT NULL
);

-- 3. TABELAS DEPENDENTES

CREATE TABLE tb_produto (
    id_produto NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_tb_produto PRIMARY KEY,
    id_categoria NUMBER NOT NULL,
    sku VARCHAR2(50) NOT NULL CONSTRAINT uk_produto_sku UNIQUE,
    nome VARCHAR2(150) NOT NULL,
    preco_unit NUMBER(10,2) NOT NULL CONSTRAINT ck_produto_preco CHECK (preco_unit > 0),
    CONSTRAINT fk_produto_categoria FOREIGN KEY (id_categoria) REFERENCES tb_categoria(id_categoria)
);

CREATE TABLE tb_venda (
    id_venda NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_tb_venda PRIMARY KEY,
    id_cliente NUMBER NOT NULL,
    id_vendedor NUMBER NOT NULL,
    dt_venda DATE DEFAULT SYSDATE NOT NULL,
    valor_liquido NUMBER(10,2),
    canal VARCHAR2(10) NOT NULL CONSTRAINT ck_venda_canal CHECK (canal IN ('APP', 'SITE', 'LOJA', 'TELEFONE')),
    status VARCHAR2(10) NOT NULL CONSTRAINT ck_venda_status CHECK (status IN ('ABERTA', 'FECHADA', 'CANCELADA')),
    CONSTRAINT fk_venda_cliente FOREIGN KEY (id_cliente) REFERENCES tb_cliente(id_cliente),
    CONSTRAINT fk_venda_vendedor FOREIGN KEY (id_vendedor) REFERENCES tb_vendedor(id_vendedor)
);

CREATE TABLE tb_venda_item (
    id_venda_item NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_tb_venda_item PRIMARY KEY,
    id_venda NUMBER NOT NULL,
    id_produto NUMBER NOT NULL,
    quantidade NUMBER NOT NULL CONSTRAINT ck_item_quantidade CHECK (quantidade > 0),
    valor_unit NUMBER(10,2) NOT NULL,
    percentual_desconto NUMBER(5,2) DEFAULT 0 NOT NULL CONSTRAINT ck_item_desconto CHECK (percentual_desconto BETWEEN 0 AND 50),
    valor_total NUMBER(10,2),
    CONSTRAINT fk_item_venda FOREIGN KEY (id_venda) REFERENCES tb_venda(id_venda) ON DELETE CASCADE,
    CONSTRAINT fk_item_produto FOREIGN KEY (id_produto) REFERENCES tb_produto(id_produto)
);

/* 
  RESULTADO DA EXECUÇÃO NO ORACLE APEX:
  Statement processed.
  Table dropped. (x6)
  Table created. (x6)
*/
